version: "1"

projects:
  - name: cliq
    environments:
      - name: Production
        services:
          - type: web
            name: cliq-backend
            runtime: docker
            repo: https://github.com/rivando-al-rasyid/cliq-backend
            plan: free
            region: singapore
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            envVars:
              - key: PORT
                value: 8080

              - key: APP_ENV
                value: production

              - key: DATABASE_URL
                fromDatabase:
                  name: cliq-postgres
                  property: connectionString

              - key: REDIS_URL
                fromService:
                  type: redis
                  name: cliq-redis
                  property: connectionString

              - key: JWT_ISSUER
                value: cliq

              - key: JWT_SECRET
                sync: false

              - key: ALLOWED_ORIGIN
                value: https://cliq-frontend.onrender.com

          - type: web
            name: cliq-frontend
            runtime: docker
            repo: https://github.com/rivando-al-rasyid/cliq-react
            plan: free
            region: singapore
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            envVars:
              - key: PORT
                value: 8080

              - key: BACKEND_URL
                value: https://cliq-backend.onrender.com

              - key: VITE_API_BASE_URL
                value: /api

              - key: VITE_API_URL
                value: /api

          - type: redis
            name: cliq-redis
            plan: free
            region: singapore
            maxmemoryPolicy: allkeys-lru
            ipAllowList: []

        databases:
          - name: cliq-postgres
            databaseName: cliq
            user: cliq_user
            plan: free
            region: singapore
